/*
 * HLS Depth Player - Standards-compliant HLS stream player with RGB + Depth unpacking
 *
 * This module handles HLS streams generated by the Python backend with side-by-side
 * RGB and RGB-packed depth frames.
 *
 * Format:
 * - Each frame is side-by-side: [RGB | Depth]
 * - RGB: Original video (left half)
 * - Depth: RGB-packed 16-bit depth (right half)
 *
 * RGB Packing (Python side):
 *   R = (depth >> 8) & 0xFF  (high byte)
 *   G = depth & 0xFF         (low byte)
 *   B = 128                  (mid-point)
 *
 * Unpacking (C++ side):
 *   float depth = (color.r * 256.0 + color.g) * scale + z_min;
 *   where scale = (z_max - z_min) / 65535.0
 *
 * SPDX-FileCopyrightText: Copyright (c) 2025, NVIDIA CORPORATION.
 * SPDX-License-Identifier: Apache-2.0
 */

#pragma once

#include <filesystem>
#include <memory>
#include <vector>
#include <mutex>
#include <atomic>

#include "video_decoder.h"

namespace vk_viewer {

/**
 * @brief Metadata for HLS depth stream
 */
struct HlsDepthMetadata {
    int rgbWidth = 0;      // Width of RGB portion (left half)
    int depthWidth = 0;    // Width of depth portion (right half)
    int height = 0;        // Frame height
    float fps = 30.0f;     // Frames per second
    double duration = 0.0; // Duration in seconds
    float zMin = 0.0f;     // Minimum depth for unpacking
    float zMax = 10.0f;    // Maximum depth for unpacking
    float scale = 0.0f;    // Scale factor: (z_max - z_min) / 65535.0
};

/**
 * @brief Decoded frame with separated RGB and depth data
 */
struct HlsDecodedFrame {
    std::vector<uint8_t> rgbData;  // RGBA RGB portion (width = total_width / 2)
    std::vector<float> depthData;  // Float depth values (width = total_width / 2)
    int width = 0;                  // Width of each portion
    int height = 0;                 // Frame height
    double timestamp = 0.0;         // Timestamp in seconds
};

/**
 * @brief HLS stream player with side-by-side RGB and depth unpacking
 *
 * Wraps VideoDecoder and adds:
 * 1. Metadata loading from JSON
 * 2. Side-by-side frame separation
 * 3. RGB-packed depth unpacking
 */
class HlsDepthPlayer {
public:
    HlsDepthPlayer();
    ~HlsDepthPlayer();

    /**
     * @brief Open HLS stream from playlist URL or file path
     * @param playlistPath Path to .m3u8 playlist or metadata JSON
     * @return true if successful
     */
    bool open(const std::filesystem::path& playlistPath);

    /**
     * @brief Load metadata from JSON file
     * @param metadataPath Path to metadata.json
     * @return true if successful
     */
    bool loadMetadata(const std::filesystem::path& metadataPath);

    /**
     * @brief Start decoding
     */
    void start();

    /**
     * @brief Stop decoding
     */
    void stop();

    /**
     * @brief Get next decoded frame with separated RGB and depth
     * @param frame Output frame
     * @return true if frame available
     */
    bool getNextFrame(HlsDecodedFrame& frame);

    /**
     * @brief Seek to timestamp
     * @param timestamp Timestamp in seconds
     * @return true if successful
     */
    bool seekToTime(double timestamp);

    /**
     * @brief Check if player is running
     */
    bool isRunning() const { return m_decoder && m_decoder->isRunning(); }

    /**
     * @brief Get metadata
     */
    const HlsDepthMetadata& getMetadata() const { return m_metadata; }

    /**
     * @brief Get current playback time
     */
    double getCurrentTime() const;

    /**
     * @brief Pause playback
     */
    void pause();

    /**
     * @brief Resume playback
     */
    void resume();

    /**
     * @brief Check if paused
     */
    bool isPaused() const { return m_decoder && m_decoder->isPaused(); }

private:
    /**
     * @brief Unpack RGB-packed depth from RGBA data
     * @param rgbaData Input RGBA data (right half of frame)
     * @param width Width of depth portion
     * @param height Height of frame
     * @return Unpacked float depth data
     */
    std::vector<float> unpackDepth(const uint8_t* rgbaData, int width, int height);

    /**
     * @brief Separate RGB and depth from side-by-side frame
     * @param frame Input decoded frame
     * @return Separated frame
     */
    HlsDecodedFrame separateFrame(const DecodedFrame& frame);

    std::unique_ptr<VideoDecoder> m_decoder;
    HlsDepthMetadata m_metadata;

    // Frame queue
    std::vector<HlsDecodedFrame> m_frameQueue;
    mutable std::mutex m_queueMutex;

    // Unpack settings
    bool m_initialized = false;
};

} // namespace vk_viewer
