/*
 * HLS Depth Player - Standards-compliant HLS stream player with Depth+Normals unpacking
 *
 * This module handles HLS streams generated by Python backend with side-by-side
 * Depth and RGB normals frames.
 *
 * Format: Depth + Normals side-by-side
 * - Left half: Grayscale 8-bit normalized depth (depth - z_min) / (z_max - z_min))
 * - Right half: RGB surface normals in [0, 255] range
 *   where each normal channel is (normal + 1.0) * 127.5
 *
 * Normals Packing (Python side):
 *   R = (normal + 1.0) * 127.5 for each channel
 *
 * SPDX-FileCopyrightText: Copyright (c) 2025, NVIDIA CORPORATION.
 * SPDX-License-Identifier: Apache-2.0
 */

#pragma once

#include <filesystem>
#include <memory>
#include <vector>
#include <mutex>
#include <atomic>

#include "video_decoder.h"

namespace vk_viewer {

struct HlsDepthMetadata {
    std::string depthVideoPath;
    int32_t frameCount = 0;
    double fps = 0.0;
    int32_t sourceWidth = 0;
    int32_t sourceHeight = 0;
    std::string modelId;
    std::string deviceSpec;
    int32_t processRes = 0;
    double processingTimeS = 0.0;
    double avgFps = 0.0;
    std::string format;
    float zMin = 0.0f;
    float zMax = 0.0f;
    float scale = 0.0f;

    // MoGe-specific fields
    bool hasNormals = false;
    bool sideBySide = false;

    // Computed values
    int32_t width = 0;
    int32_t height = 0;
    int32_t rgbWidth = 0;   // RGB video width (same as width for side-by-side)
    double duration = 0.0;  // Total duration in seconds
};

struct HlsDecodedFrame {
    std::vector<uint8_t> rgbData;       // Reconstructed RGB video data
    std::vector<float> depthData;       // Depth values in meters
    std::vector<uint8_t> normalsData;   // Surface normals
    int width = 0;
    int height = 0;
    double timestamp = 0.0;
};

class HlsDepthPlayer {
public:
    HlsDepthPlayer();
    ~HlsDepthPlayer();

    bool open(const std::filesystem::path& playlistPath);
    bool loadMetadata(const std::filesystem::path& metadataPath);
    void start();
    void stop();

    bool getNextFrame(HlsDecodedFrame& frame);
    bool seekToTime(double timestamp);

    bool isRunning() const { return m_decoder && m_decoder->isRunning(); }
    const HlsDepthMetadata& getMetadata() const { return m_metadata; }
    double getCurrentTime() const;
    void pause();
    void resume();

private:
    std::vector<float> unpackDepthFromGrayscale(const uint8_t* grayscaleData, int width, int height);
    HlsDecodedFrame separateFrame(const DecodedFrame& frame);

    std::unique_ptr<VideoDecoder> m_decoder;
    HlsDepthMetadata m_metadata;

    std::vector<HlsDecodedFrame> m_frameQueue;
    mutable std::mutex m_queueMutex;

    bool m_initialized = false;
};

}
